version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: todos
      POSTGRES_PASSWORD: todos
      POSTGRES_DB: todos
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todos" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
    container_name: rabbitmq-todos-local
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  pg_dev_data:
    driver: local